import { createIconSetFromIcoMoon } from 'react-native-vector-icons';

import config from './selection.json';

const Icomoon = createIconSetFromIcoMoon(config);

export const names = [
    'arrow-down',
    'attachment',
    'back',
    'bell-off',
    'bell',
    'box-fill',
    'box',
    'calculator',
    'calendar',
    'camera-fill',
    'camera',
    'cart-fill',
    'cart',
    'check-fill',
    'check',
    'close',
    'delivery',
    'discount',
    'dowload',
    'filter',
    'help',
    'home-fill',
    'home',
    'image',
    'info-circle',
    'infor-fill',
    'infor-user',
    'infor-user',
    'infor',
    'logout',
    'mail-send',
    'mail',
    'mark',
    'menu',
    'message',
    'microphone',
    'new-message',
    'news',
    'order-fill',
    'order',
    'pencil',
    'phone',
    'play',
    'plus',
    'profile-fill',
    'profile',
    'search',
    'send',
    'shop-fill',
    'shop',
    'star',
    'stop',
    'store',
    'support',
    'trash',
    'view-off',
    'view',
];
export default Icomoon;
